import Head from "next/head";
import React, { useEffect, useState } from "react";
import { useRouter } from "next/router";
import { Box, Flex, Grid } from "@chakra-ui/react";
import { usePaginator } from "chakra-paginator";

import Movie from "../../components/Movie";
import Pagination from "../../components/Pagination";
import scrollToTop from "../../components/utilities/ScrolltoTop";
import Layout from "../../components/Layout";

import moviesApi from "../../api/movies";

export default function Trending() {
  const router = useRouter();
  const [movies, setMovies] = useState({});
  const movieId = router.query.id;

  const { currentPage, setCurrentPage } = usePaginator({
    initialState: { currentPage: 1 },
  });

  useEffect(() => {
    getSimilarMovies();
  }, [currentPage]);

  const getSimilarMovies = async () => {
    try {
      const response = await moviesApi.getSimilarMovies(movieId, currentPage);
      setMovies(response.data);
    } catch (error) {
      console.log(error);
    }
  };

  const handlePageChange = (pageNumber) => {
    setCurrentPage(pageNumber);
    scrollToTop();
  };

  return (
    <Layout>
      <Head>
        <title>Similar-{movieId} - Master-Byte</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Grid templateColumns="repeat(5,1fr)" gap="1rem" mt="2rem">
        {movies?.results?.map((movie) => (
          <Movie
            key={movie?.id}
            movie={movie}
            onNavigate={() => router.push(`/movie-details/${movie?.id}`)}
          />
        ))}
      </Grid>

      <Flex mt={10} justify="flex-end">
        <Pagination
          pagesQuantity={movies?.total_pages}
          currentPage={currentPage}
          onPageChange={handlePageChange}
        />
      </Flex>
    </Layout>
  );
}
